# Generated by Django 5.0.1 on 2024-02-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('ochilgan_sana', models.DateField()),
                ('dars_vaqti', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel_raqam', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('raqam', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('narx', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel_raqam', models.CharField(max_length=30)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.guruh')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_summasi', models.FloatField()),
                ('qarz', models.FloatField()),
                ('chegirma', models.PositiveSmallIntegerField()),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.guruh')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.oquvchi')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ustoz'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='xona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.xona'),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.yonalish'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.yonalish'),
        ),
    ]
